import Head from 'next/head';
import Header from '../Header/Header';


const Layout = ({children, page}) => {
  return (
    <div >
      <Head>
        <title> Alba Portfolio - {page}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    
      <div >
        <Header/>
      </div>
        {children}
    </div>
  )
}

export default Layout